//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileGridGames.ResX {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MobileGridGames.ResX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        internal static string AppSettingsDarkTheme {
            get {
                return ResourceManager.GetString("AppSettingsDarkTheme", resourceCulture);
            }
        }
        
        internal static string AppSettingsIntro {
            get {
                return ResourceManager.GetString("AppSettingsIntro", resourceCulture);
            }
        }
        
        internal static string AppSettingsHideGrid {
            get {
                return ResourceManager.GetString("AppSettingsHideGrid", resourceCulture);
            }
        }
        
        internal static string BrowsePicture {
            get {
                return ResourceManager.GetString("BrowsePicture", resourceCulture);
            }
        }
        
        internal static string ChooseEightPictures {
            get {
                return ResourceManager.GetString("ChooseEightPictures", resourceCulture);
            }
        }
        
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard1Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard1Description", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard1Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard1Name", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard2Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard2Description", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard2Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard2Name", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard3Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard3Description", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard3Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard3Name", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard4Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard4Description", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard4Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard4Name", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard5Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard5Description", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard5Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard5Name", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard6Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard6Description", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard6Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard6Name", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard7Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard7Description", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard7Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard7Name", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard8Description {
            get {
                return ResourceManager.GetString("DefaultMatchingCard8Description", resourceCulture);
            }
        }
        
        internal static string DefaultMatchingCard8Name {
            get {
                return ResourceManager.GetString("DefaultMatchingCard8Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare10Name {
            get {
                return ResourceManager.GetString("DefaultSquare10Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare11Name {
            get {
                return ResourceManager.GetString("DefaultSquare11Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare12Name {
            get {
                return ResourceManager.GetString("DefaultSquare12Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare13Name {
            get {
                return ResourceManager.GetString("DefaultSquare13Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare14Name {
            get {
                return ResourceManager.GetString("DefaultSquare14Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare15Name {
            get {
                return ResourceManager.GetString("DefaultSquare15Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare1Name {
            get {
                return ResourceManager.GetString("DefaultSquare1Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare2Name {
            get {
                return ResourceManager.GetString("DefaultSquare2Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare3Name {
            get {
                return ResourceManager.GetString("DefaultSquare3Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare4Name {
            get {
                return ResourceManager.GetString("DefaultSquare4Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare5Name {
            get {
                return ResourceManager.GetString("DefaultSquare5Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare6Name {
            get {
                return ResourceManager.GetString("DefaultSquare6Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare7Name {
            get {
                return ResourceManager.GetString("DefaultSquare7Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare8Name {
            get {
                return ResourceManager.GetString("DefaultSquare8Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquare9Name {
            get {
                return ResourceManager.GetString("DefaultSquare9Name", resourceCulture);
            }
        }
        
        internal static string DefaultSquareEmpty {
            get {
                return ResourceManager.GetString("DefaultSquareEmpty", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        internal static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        internal static string Eleven {
            get {
                return ResourceManager.GetString("Eleven", resourceCulture);
            }
        }
        
        internal static string FaceDown {
            get {
                return ResourceManager.GetString("FaceDown", resourceCulture);
            }
        }
        
        internal static string Fifteen {
            get {
                return ResourceManager.GetString("Fifteen", resourceCulture);
            }
        }
        
        internal static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        internal static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        internal static string Fourteen {
            get {
                return ResourceManager.GetString("Fourteen", resourceCulture);
            }
        }
        
        internal static string GameReady {
            get {
                return ResourceManager.GetString("GameReady", resourceCulture);
            }
        }
        
        internal static string GridGames {
            get {
                return ResourceManager.GetString("GridGames", resourceCulture);
            }
        }
        
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static string HelpContentPairs {
            get {
                return ResourceManager.GetString("HelpContentPairs", resourceCulture);
            }
        }
        
        internal static string HelpContentSquares {
            get {
                return ResourceManager.GetString("HelpContentSquares", resourceCulture);
            }
        }
        
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        internal static string LoadedCustomPictures {
            get {
                return ResourceManager.GetString("LoadedCustomPictures", resourceCulture);
            }
        }
        
        internal static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        internal static string Matched {
            get {
                return ResourceManager.GetString("Matched", resourceCulture);
            }
        }
        
        internal static string MatchingWonInMoves {
            get {
                return ResourceManager.GetString("MatchingWonInMoves", resourceCulture);
            }
        }
        
        internal static string MissingMatchingGamePictureDetails {
            get {
                return ResourceManager.GetString("MissingMatchingGamePictureDetails", resourceCulture);
            }
        }
        
        internal static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string NoFolderSelected {
            get {
                return ResourceManager.GetString("NoFolderSelected", resourceCulture);
            }
        }
        
        internal static string NoMovePossible {
            get {
                return ResourceManager.GetString("NoMovePossible", resourceCulture);
            }
        }
        
        internal static string NumberSize {
            get {
                return ResourceManager.GetString("NumberSize", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        internal static string Pairs {
            get {
                return ResourceManager.GetString("Pairs", resourceCulture);
            }
        }
        
        internal static string PairsGameHelp {
            get {
                return ResourceManager.GetString("PairsGameHelp", resourceCulture);
            }
        }
        
        internal static string PairsSettings {
            get {
                return ResourceManager.GetString("PairsSettings", resourceCulture);
            }
        }
        
        internal static string PairsWelcome {
            get {
                return ResourceManager.GetString("PairsWelcome", resourceCulture);
            }
        }
        
        internal static string PicturePath {
            get {
                return ResourceManager.GetString("PicturePath", resourceCulture);
            }
        }
        
        internal static string PlaySoundMatch {
            get {
                return ResourceManager.GetString("PlaySoundMatch", resourceCulture);
            }
        }
        
        internal static string PlaySoundNotMatch {
            get {
                return ResourceManager.GetString("PlaySoundNotMatch", resourceCulture);
            }
        }
        
        internal static string RestartGame {
            get {
                return ResourceManager.GetString("RestartGame", resourceCulture);
            }
        }
        
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        internal static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        internal static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        internal static string ShowCustomPictures {
            get {
                return ResourceManager.GetString("ShowCustomPictures", resourceCulture);
            }
        }
        
        internal static string ShowNumbers {
            get {
                return ResourceManager.GetString("ShowNumbers", resourceCulture);
            }
        }
        
        internal static string ShowPicture {
            get {
                return ResourceManager.GetString("ShowPicture", resourceCulture);
            }
        }
        
        internal static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        internal static string Sixteen {
            get {
                return ResourceManager.GetString("Sixteen", resourceCulture);
            }
        }
        
        internal static string Squares {
            get {
                return ResourceManager.GetString("Squares", resourceCulture);
            }
        }
        
        internal static string SquaresGameHelp {
            get {
                return ResourceManager.GetString("SquaresGameHelp", resourceCulture);
            }
        }
        
        internal static string SquaresSettings {
            get {
                return ResourceManager.GetString("SquaresSettings", resourceCulture);
            }
        }
        
        internal static string SquaresSettingsInstructions {
            get {
                return ResourceManager.GetString("SquaresSettingsInstructions", resourceCulture);
            }
        }
        
        internal static string SquaresWelcome {
            get {
                return ResourceManager.GetString("SquaresWelcome", resourceCulture);
            }
        }
        
        internal static string SquaresWonInGoes {
            get {
                return ResourceManager.GetString("SquaresWonInGoes", resourceCulture);
            }
        }
        
        internal static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        internal static string ThatsMatch {
            get {
                return ResourceManager.GetString("ThatsMatch", resourceCulture);
            }
        }
        
        internal static string Thirteen {
            get {
                return ResourceManager.GetString("Thirteen", resourceCulture);
            }
        }
        
        internal static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        internal static string TurnedUp {
            get {
                return ResourceManager.GetString("TurnedUp", resourceCulture);
            }
        }
        
        internal static string Twelve {
            get {
                return ResourceManager.GetString("Twelve", resourceCulture);
            }
        }
        
        internal static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        internal static string UnexpectedDataInFile {
            get {
                return ResourceManager.GetString("UnexpectedDataInFile", resourceCulture);
            }
        }
        
        internal static string UnmatchedTurnedBack {
            get {
                return ResourceManager.GetString("UnmatchedTurnedBack", resourceCulture);
            }
        }
        
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        internal static string WelcomeInstructions {
            get {
                return ResourceManager.GetString("WelcomeInstructions", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string AppSettingsDarkThemeInstructions {
            get {
                return ResourceManager.GetString("AppSettingsDarkThemeInstructions", resourceCulture);
            }
        }
        
        internal static string AppSettingsHideGridInstructions {
            get {
                return ResourceManager.GetString("AppSettingsHideGridInstructions", resourceCulture);
            }
        }
        
        internal static string PictureAspectLabel {
            get {
                return ResourceManager.GetString("PictureAspectLabel", resourceCulture);
            }
        }
        
        internal static string PictureAspectInstructions {
            get {
                return ResourceManager.GetString("PictureAspectInstructions", resourceCulture);
            }
        }
        
        internal static string FillCardAndClip {
            get {
                return ResourceManager.GetString("FillCardAndClip", resourceCulture);
            }
        }
        
        internal static string FillCardWithoutClipping {
            get {
                return ResourceManager.GetString("FillCardWithoutClipping", resourceCulture);
            }
        }
        
        internal static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        internal static string Largest {
            get {
                return ResourceManager.GetString("Largest", resourceCulture);
            }
        }
        
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        internal static string ShowFullPicture {
            get {
                return ResourceManager.GetString("ShowFullPicture", resourceCulture);
            }
        }
        
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
    }
}
